DROP DATABASE NutrilogDB;

CREATE DATABASE NutrilogDB;

USE NutrilogDB;

CREATE TABLE Person(
	Id INTEGER(9) NOT NULL,
	FirstName VARCHAR(255),
	LastName VARCHAR(255) NOT NULL,
	Gender CHAR,
	DOB DATETIME,
	PRIMARY KEY(Id) 
);

CREATE TABLE Event(
	Id INTEGER NOT NULL,
	EventDate DATE,
	EventType VARCHAR(255) NOT NULL,
	PersonId INTEGER NOT NULL,
	Units INTEGER,
	Weight FLOAT,
	Urine BOOLEAN,
	Stool BOOLEAN,
	PRIMARY KEY (Id),
	FOREIGN KEY (PersonId) REFERENCES Person (Id)
);

CREATE TABLE EventType(
	Id INTEGER NOT NULL,
	EventType VARCHAR(255) NOT NULL,
	FOREIGN KEY (Id) REFERENCES Event (Id)
);






