DROP DATABASE NutrilogDB;

CREATE DATABASE NutrilogDB;

USE NutrilogDB;

CREATE TABLE Person(
	Id INTEGER NOT NULL,
	FirstName VARCHAR(255)NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	DOB DATE NOT NULL,
	PRIMARY KEY(Id) 
);

CREATE TABLE AppUser(
	UserId INTEGER NOT NULL,
	UserName VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	PRIMARY KEY (UserId),
	FOREIGN KEY (UserId) REFERENCES Person(Id)
);

CREATE TABLE Patient(
	PatientId INTEGER NOT NULL,
	Gender CHAR NOT NULL,
	Weight FLOAT,
	PRIMARY KEY (PatientId),
	FOREIGN KEY (PatientId) REFERENCES Person (Id)
);

CREATE TABLE PatientHistory(
	HistoryId INTEGER NOT NULL,
	PatientId INTEGER NOT NULL,
	EventId INTEGER NOT NULL,
	PRIMARY KEY (HistoryId),
	FOREIGN KEY (PatientId) REFERENCES Patient(PatientId)
);

CREATE TABLE HistoryEvent(
	EventId INTEGER NOT NULL,
	HistoryId INTEGER NOT NULL,
	EventName VARCHAR(255) NOT NULL,
	FoodUnit FLOAT,
	Urine BOOLEAN,
	Stool BOOLEAN,
	Weight FLOAT,
	PRIMARY KEY (EventId),
	FOREIGN KEY (HistoryId) REFERENCES PatientHistory (HistoryId)
);





